[mysql]
username = "pandagpt"
password = "3375991Qa"
host = "localhost"
dialect = "mysql"
port = 3306
database = "QuillaGPT"
query = { charset = "utf8mb4" }
[pinecone]
PINECONE_API_KEY = "pcsk_43WL6a_2MeSgnY8w1MSHbwEW4X2FQqqN7qKR4wsi2HXYb2KCBhg4XJ7yMuRgLSForwQGgs"
[google_auth]
cliend_id = "887178367133-0gl3pg615otu9c3ufqhihj2fj3igpdvr.apps.googleusercontent.com"
cliend_secret = "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"
[auth]
redirect_uri = "http://pandagpt.ip-ddns.com:8501/oauth2callback"
cookie_secret = "123"
client_id = "887178367133-0gl3pg615otu9c3ufqhihj2fj3igpdvr.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"